apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red1
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red1",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.1.0/24",
        "range_start": "10.0.1.20",
        "range_end": "10.0.1.100",
        "gateway": "10.0.1.10"
      }
    }

