apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red3
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red3",
      "type": "ipvlan",
      "master": "enp4s0",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.3.0/24",
        "rangeStart": "10.0.3.20",
        "rangeEnd": "10.0.3.100"
      }
    }
