apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red2",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.2.0/24",
        "range_start": "10.0.2.20",
        "range_end": "10.0.2.100",
        "gateway": "10.0.2.10"
      }
    }

