apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red3
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red3",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.3.0/24",
        "range_start": "10.0.3.20",
        "range_end": "10.0.3.100"
      }
    }
