apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red4
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red4",
      "type": "bridge",
      "bridge": "bridge-red4",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.4.0/24",
        "rangeStart": "10.0.4.20",
        "rangeEnd": "10.0.4.100"
      }
    }
