apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red2",
      "type": "bridge",
      "bridge": "bridge-red2",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.2.0/24",
        "rangeStart": "10.0.2.20",
        "rangeEnd": "10.0.2.100"
      }
    }
