apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red4
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red4",
      "type": "ipvlan",
      "master": "cni0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.4.0/24",
        "range_start": "10.0.4.20",
        "range_end": "10.0.4.100"
      }
    }
