apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red1-rc
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red1",
      "type": "ipvlan",
      "master": "enp1s0",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.0.1.10/24"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red2-rc
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red2",
      "type": "ipvlan",
      "master": "enp1s0",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.0.2.10/24"
          }
        ]
      }
    }

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-rc-rb
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-rc-rb",
      "type": "ipvlan",
      "master": "enp1s0",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.2.0.20/24"
          }
        ]
      }
    }