apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red3-rd
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red3",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.3.0/24",
        "range_start": "10.0.3.10",
        "range_end": "10.0.3.10"
      }
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red4-rd
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red4",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.4.0/24",
        "range_start": "10.0.4.10",
        "range_end": "10.0.4.10"
      }
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-rd-rb
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-rd-rb",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.3.0.0/24",
        "range_start": "10.3.0.20",
        "range_end": "10.3.0.20"
      }
    }
