apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-ra-rb
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-ra-rb",
      "type": "ipvlan",
      "master": "enp8s0",
      "mode": "l3",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.1.0.10/24"
          }
        ]
      }
    }



---   


apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-servidor-ra
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-servidor",
      "type": "ipvlan",
      "master": "enp9s0",
      "mode": "l3",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.100.0.10/24"
          }
        ]
      }
    }



---

# interfaz para el servidor

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-servidor
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-servidor",
      "type": "ipvlan",
      "master": "enp9s0",
      "mode": "l3",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.100.0.2/24"
          }
        ]
      }
    }


---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-fluentd-ra
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "fluentd",
      "type": "ipvlan",
      "master": "enp1s0",
      "mode": "l3",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.200.0.10/24"
          }
        ]
      }
    }
