apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-rb-rc
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-rc-rb",
      "type": "ipvlan",
      "master": "cni0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "10.2.0.0/24",
        "range_start": "10.2.0.10",
        "range_end": "10.2.0.10"
      }
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-rb-rd
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-rd-rb",
      "type": "ipvlan",
      "master": "cni0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "10.3.0.0/24",
        "range_start": "10.3.0.10",
        "range_end": "10.3.0.10"
      }
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-rb-ra
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-ra-rb",
      "type": "ipvlan",
      "master": "cni0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "10.1.0.0/24",
        "range_start": "10.1.0.20",
        "range_end": "10.1.0.20"
      }
    }
