apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red1-rc
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red1",
      "type": "ipvlan",
      "master": "enp1s0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.1.0/24",
        "range_start": "10.0.1.10",
        "range_end": "10.0.1.10",
        "routes": [
          {
            "dst": "10.0.1.0/24",
            "gw": "10.0.1.10"
          },
          {
            "dst": "10.0.2.0/24",
            "gw": "10.0.2.10"
          },
          {
            "dst": "10.0.3.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.0.4.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.1.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.2.0.0/24",
            "gw": "10.2.0.20"
          },
          {
            "dst": "10.3.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.100.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.200.0.0/24",
            "gw": "10.2.0.10"
          }
        ]
      }
    }


---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-red2-rc
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red2",
      "type": "ipvlan",
      "master": "enp1s0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.2.0/24",
        "range_start": "10.0.2.10",
        "range_end": "10.0.2.10"
        "routes": [
          {
            "dst": "10.0.1.0/24",
            "gw": "10.0.1.10"
          },
          {
            "dst": "10.0.2.0/24",
            "gw": "10.0.2.10"
          },
          {
            "dst": "10.0.3.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.0.4.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.1.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.2.0.0/24",
            "gw": "10.2.0.20"
          },
          {
            "dst": "10.3.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.100.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.200.0.0/24",
            "gw": "10.2.0.10"
          }
        ]
      }
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-rc-rb
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-rc-rb",
      "type": "ipvlan",
      "master": "enp1s0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "10.2.0.0/24",
        "range_start": "10.2.0.20",
        "range_end": "10.2.0.20"
        "routes": [
          {
            "dst": "10.0.1.0/24",
            "gw": "10.0.1.10"
          },
          {
            "dst": "10.0.2.0/24",
            "gw": "10.0.2.10"
          },
          {
            "dst": "10.0.3.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.0.4.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.1.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.2.0.0/24",
            "gw": "10.2.0.20"
          },
          {
            "dst": "10.3.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.100.0.0/24",
            "gw": "10.2.0.10"
          },
          {
            "dst": "10.200.0.0/24",
            "gw": "10.2.0.10"
          }
        ]
      }
    }
---
