apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-ra-rb
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-ra-rb",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.1.0.0/24",
        "range_start": "10.1.0.10",
        "range_end": "10.1.0.10"
      }
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-servidor-ra
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-servidor-ra",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.100.0.0/24",
        "range_start": "10.100.0.10",
        "range_end": "10.100.0.10"
      }
    }

---

# interfaz para el servidor

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-servidor
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "red-servidor",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.100.0.0/24",
        "range_start": "10.100.0.2",
        "range_end": "10.100.0.2"
      }
    }
---



