apiVersion: v1
kind: Pod
metadata:
  name: server-red1
  annotations:
    k8s.v1.cni.cncf.io/networks: default/bridge-red1
spec:
  containers:
  - name: server-red1
    image: miguelliceon/docker-to-k8s:client
    command: ["/entrypoints/ep_red1.sh","/bin/sleep", "infinity"]
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
  imagePullSecrets:
  - name: dockerhub-secret